# render.yaml for the nerimity-server application
# This blueprint defines the backend services and connects to existing infrastructure.

services:
  # The API Server
  - type: web
    name: cannacured-api
    runtime: node
    plan: standard
    healthCheckPath: /health # Add a /health route to your Express app for monitoring
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm prisma:migrate_deploy && pnpm start-dist-api
    envVars:
      - fromGroup: cannacured-shared-env # Pulls static secrets (JWT_SECRET, etc.)
      - key: DATABASE_URL
        fromDatabase:
          name: cannacured-db
          property: connectionString
      - key: DATABASE_DIRECT_URL # Add this for Prisma migrations
        fromDatabase:
          name: cannacured-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: cannacured-redis
          property: connectionString
      - key: NODE_OPTIONS
        value: '--max-old-space-size=1024'

  # The WebSocket Server
  - type: web
    name: cannacured-ws
    runtime: node
    plan: pro
    healthCheckPath: /health
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start-dist-ws
    envVars:
      # This service connects to the exact same infrastructure
      - fromGroup: cannacured-shared-env
      - key: DATABASE_URL
        fromDatabase:
          name: cannacured-db
          property: connectionString
      - key: DATABASE_DIRECT_URL # Add this for Prisma migrations
        fromDatabase:
          name: cannacured-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: cannacured-redis
          property: connectionString
      - key: NODE_OPTIONS
        value: '--max-old-space-size=1024'
